databaseChangeLog:
  - changeSet:
      id: 1
      author: kevin
      changes:
          - createTable:
              tableName: original_document
              columns:
                - column:
                    name: id
                    type: int
                    constraints:
                      primaryKey: true
                      nullable: false
                - column:
                   name: file_name
                   type: nvarchar(150)
                   constraints:
                     nullable: false
                - column:
                   name: document_body
                   type: clob
                   constraints:
                     nullable: false
                - column:
                    name: current_phase
                    type: nvarchar(150)
                    constraints:
                      nullable: false
                - column:
                    name: received_date
                    type: datetime
                    constraints:
                      nullable: false